apiVersion: 1

datasources:
  - name: DocuMind Postgres
    uid: documind-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: documind_db
    user: documind_user
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: documind_pass
